### ISSUE TITLE
delist the action on the marketplace

### ISSUE THREAD

**Issue by Amndeep7** [mitre/inspec_tools_action#2]
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace

archive the repo afterwards

blocked by https://github.com/mitre/saf/issues/1 cause we have to make sure all the functionality from inspec_tools is in saf_cli first

**Comment by Amndeep7** [comment]
additionally need to remove it from the saf site

**Comment by em-c-rod** [comment]
Delisted.
